# Generated by Django 5.0 on 2023-12-21 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Empleado')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=255, verbose_name='Apellido 1')),
                ('apellido2', models.CharField(max_length=255, verbose_name='Apellido 2')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Marca ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marcador_Byte.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
