# Generated by Django 5.0 on 2023-12-22 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcador_Byte', '0002_alter_empleado_empleado_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas2',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Marca ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marcador_Byte.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
